networks:
  mongo-express-database-network:
  cache-movies-network:
  database-movies-network:

volumes:
  profiledata:

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
      environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
      - REDIS_URI=redis://cache
      - ENABLE_WRITING_HANDLERS=false
    ports:
      - '9000:9000'
    networks:
       - cache-movies-network
       - database-movies-network
    depends_on:
      - database

  cache:
    container_name: redis
    image: redis:alpine

  database:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
       - database-movies-network
       - mongo-express-database-network
    volumes: 
       - profiledata:/data/db

  mongo-seed:
    container_name: mongo-seed
    image: mongo:8.0-rc
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./seeding.json
        target: /seeding.json
    networks:
      - database-mongo-seed-network
    command:
      mongoimport --authenticationDatabase=admin --db tmdb_movies --collection movies --drop --file /seeding.json --jsonArray mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
    profiles:
      - development

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017/
    networks:
       - mongo-express-database-network
    depends_on:
      - database
    profiles:
      - development

